### ISSUE TITLE
Server Crash - at elec332.core.grid.v2.AbstractGridHandler.checkChunkLoad(AbstractGridHandler.java:171)

### ISSUE THREAD

**Issue by ProsperCraft** [Elecs-Mods/ElecCore#65]
http://pastebin.com/t38wZ6bn

ElecCore-1.10.2-1.6.328

Description: Exception in server tick loop

java.lang.IllegalStateException
    at elec332.core.grid.v2.AbstractGridHandler.checkChunkLoad(AbstractGridHandler.java:171)
    at elec332.core.grid.v2.internal.GridEventInputHandler.tickEnd(GridEventInputHandler.java:108)
    at elec332.core.grid.v2.internal.GridEventHandler.serverTick(GridEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_369_GridEventHandler_serverTick_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:130)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:99)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

**Comment by ProsperCraft** [comment]
http://pastebin.com/7Uqb4nK2

http://pastebin.com/MdmddpDw

http://pastebin.com/uyNGjHvS

Crash keeps happening, trying to pinpoint it.

**Comment by ProsperCraft** [comment]
http://pastebin.com/kgKbgXt4

**Comment by ProsperCraft** [comment]
http://pastebin.com/jU0UsxGY

http://pastebin.com/48A7xh7Z

**Comment by xlxAciDxlx** [comment]
Did you break a block or anything like that before the crash? Or did it just randomly happen/start happening?

**Comment by ProsperCraft** [comment]
Randomly started, now it happens every time Rhaeck logs in, would you like the server files?

**Comment by ProsperCraft** [comment]
ok, so I disabled sponge and the crash is no longer happening, cloning this to sponge github.

**Comment by ProsperCraft** [comment]
Then I re-enabled sponge and he was able to log in....so may not be clearly sponge.

**Comment by Elec332** [comment]
The core of this issue may be sponge...

**Comment by kashike** [comment]
Please elaborate, @Elec332.

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/e34895daf71751202c6eea498069ca76

We keep crashing over and over...both Hermitcraft and allthemods.

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/3334179578d33b69c7fc3afcf325e4ad

**Comment by bloodmc** [comment]
@Elec332 Let me know if you find what the issue is so I can investigate on our end.

Thanks!

**Comment by Elec332** [comment]
@ProsperCraft The NPE has been fixed over a week ago, but the modpacks haven't been updated.

If you run into the IllegalStateExeption again, please post the entire log, the crash report doesnt tell me enough here.

**Comment by ProsperCraft** [comment]
Thank you for pointing out I needed to give new crashlogs, here is a new batch with the updated mod.

https://gist.github.com/ProsperCraft/8b04a7eb6680c6f3bc497abb54f29bf7
https://gist.github.com/ProsperCraft/7f0d4547ac475f5e248cf56cb8ac442f
https://gist.github.com/ProsperCraft/c31e0de5693daeeaf8b44b6137500d16
https://gist.github.com/ProsperCraft/d8ae8fdcbb96c394663c329b5f4d4148
https://gist.github.com/ProsperCraft/5dbe3c27787d26e35422c7456bd6d65f

[prospercraftlogs.tar.gz](https://github.com/Elecs-Mods/ElecCore/files/560571/prospercraftlogs.tar.gz)

**Comment by ProsperCraft** [comment]
Those were all from Allthemods 1.40b

Here is one from Hermitpack 1.2.1 also with the updated mod
https://gist.github.com/ProsperCraft/172575cbd67bbcff91f62fe4c56227b6

**Comment by Elec332** [comment]
I do not need those   crashlogs, just the server log ;)
The tar.gz file contains many log files, but since it contains over 200 files, im not gonna figure out which of them contains the crash. So if you could please upload a log file containing this crash, that would be great.

**Comment by ProsperCraft** [comment]
Crash report shows time, match that with the log and bam?

**Comment by Elec332** [comment]
Well, not with the log files you rpvided, I EG have a crash from "Time: 10/29/16 3:05 PM", but you didnt provide a log file from that time. So if you can please just post a crashlog with the linked log files, that would be great.

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/b0923b93745ec196a450181cc30ca241

Found one that didn't get rotated out!

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/8884ad12f53a9af7096f1f10de7f0f7c

Server log

**Comment by LemADEC** [comment]
Issue is reproduced without sponge. It happens when players are moving away from a base.
crash report: https://gist.github.com/LemADEC/4d5cef23c5d3741db718f9fe92aa8940
server logs: https://gist.github.com/LemADEC/969f51caf2fb37f93ffe0ddec86d5f47

**Comment by phit** [comment]
just had the same thing happen to my server with Infinity Lite 1.10
crash & server log: https://gist.github.com/phit/0cc10f01da143a3efbfb11616c21eb9f

**Comment by phit** [comment]
so every time the affected user logs in it crashes the server, I could go to the area though without crashing
here's the setup in question http://i.imgur.com/seGL25u.png

edit: once I loaded the chunk by being there he could log on, we moved the machine away from the chunk boundary, hoping that fixed it

**Comment by LemADEC** [comment]
And this is why you should never build near chunk borders, ever...

**Comment by phit** [comment]
update: crashed again same setup no longer anywhere near a chunk boundary

**Comment by Elec332** [comment]
Hmmmm, interesting....

**Comment by Elec332** [comment]
@phit Your issue has been fixed over 2 weeks ago, just update ElecCore to the latest version...

**Comment by Elec332** [comment]
This means the issue can still only be reproduced when Sponge is installed...

**Comment by lilmoefow** [comment]
Did you miss @LemADEC comment where  they reproduced the crash with out Sponge??

**Comment by Evinsta** [comment]
I am running the latest version of ElecCore and also the latest version of spongeforge-1.10.2-2123-5.1.0-BETA-1879 and still get the crash, thought that updating to the latest spongeforge might have fixed it due to the large number of updates in the changelog

**Comment by knoxz** [comment]
Excat same issue on the MYM Network with the latest direwolf20 modpack on 1.10.2 and SpongeForge.

**Comment by 016Nojr** [comment]
Can confirm what @knoxz said

**Comment by Elec332** [comment]
@Evinsta , @knoxz & @016Nojr , can any of you reproduce this _without_ sponge?
If so, please tell me, and show me the new logs

**Comment by LemADEC** [comment]
@Elec332 what's the issue with my reproduction without sponge?

**Comment by phit** [comment]
@LemADEC your crash was already fixed in 358c9ffe2d427c0256b1e8a02e7eb4240eb39dba, this is a different issue only happening on with sponge

**Comment by lilmoefow** [comment]
@ProsperCraft  can I ask why you closed this?  are you not having this issue any more? if not can you let me know which versions of sponge/deepresonance you are using?

**Comment by Blaedyn** [comment]
what is sponge/deep resonance? I have been playing on my curse client on a self made modpack, going back to the previous mod for eleccore seemed to work, as in my game would launch but my crafting table doesnt work,


sorry I'm just not very good at checking back on things,
Blaedyn


________________________________
