### ISSUE TITLE
Crash on Right Click - 1.10.2 Forge 202

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Elecs-Mods/ElecCore#80]
https://gist.github.com/P3rf3ctXZer0/23cb3f69f7e35cc91de2d5609f87d2dc

**Comment by ghost** [comment]
im getting the same crash,
right clicked a door and a crate boom
wierdly my test server is fine, i dont crash on that
http://pastebin.com/sXuRHCXu
I know it says its fixed but this is forge 202 mc 10.2 and version ElecCore-1.10.2-1.6.378 which is the newest file on curse and the project site.

The issue seems to be only when you right click with an empty hand, if you have an item in your hand all is well...empty hand and bam client crashes
i see its fixed in the code? is there a release somewhere chap?

EDIT:
i downloaded the 1.10 branch
extracted it
cmd in to it
ran gradlew build
went to build / lib and retrieved the file
that worked...no more bug so yeah the new code works chap, just its not on curse yet :)
(left solution in detail for others)

**Comment by zackeezy** [comment]
How long before the fix is posted to curse?

**Comment by CMCarlsen** [comment]
I'm still receiving this error as well. And from the looks of it, issue #81 is the same.

Any ETA on the push for the fix? This one's kind of a major crash.

Thanks! :+1:

**Comment by Elec332** [comment]
Fixed in latest release
